### ISSUE TITLE
Configuration to pull down a site from Pantheon

### ISSUE THREAD

**Issue by wizonesolutions** [hashbangcode/ansible-role-pantheon-cli#1]
So, as I mentioned a couple weeks ago, I'd like to look at adding support for specifying a site and env on Pantheon and having the role pull down the DB and files (and maybe optionally the code, since people might use version control) automatically according to some configuration. It could use the latest backups and optionally allow the user to specify files they've already downloaded directly or something. Probably start there...more flexibility in what gets downloaded from Pantheon would be cool, maybe even taking a backup on the spot (if they have perms) and then downloading that when it's done...but first I'd need an MVP.

Is this the right place for this issue, or is it more related to spinning Vlad itself up?

I'm planning to work on this gradually, and I'm opening an issue to get implementation tips. I have to write tests too I think?

**Comment by wizonesolutions** [comment]
You know, I'm thinking about this. Shouldn't the Pantheon pull-down functionality be in Vlad core, or at least in a different role? I don't think it really fits conceptually into this role. I'm just going to start implementing it as a new role or something, and then once you answer I can refactor a bit and put it where it should be.

**Comment by dixhuit** [comment]
Sorry for the slow reply - Pantheon CLI is not a major part of my workflow right now so I wasn't sure how best to answer your question given the gaps in my knowledge.

I think you may be right though, _this_ role may be best left as a minimal installation-only role with further functionality located in a new role (either on Galaxy or in Vlad).

I guess it really depends on what Vlad vars you'll need access to - I guess you'll want access to Vlad database vars so that instantly narrows the scope of where else such a role could be used (i.e. nowhere other than Vlad :)). Perhaps try to develop this as a custom play initially and then consider next steps once you're happy with how it's performing and can review how you ended up implementing it? (that's how I usually develop new Vlad features)

**Comment by wizonesolutions** [comment]
What do you think about me doing it as an in-Vlad role to start and opening up a PR for discussion? Not sure if custom plays are as easy to PR, guessing they are gitignored.

**Comment by dixhuit** [comment]
> Not sure if custom plays are as easy to PR, guessing they are gitignored.

True but there's nothing to stop you making your custom play a public repo and linking to it from Vlad's issue queue.

Recent changes in Vlad to better support external roles make this kind of development a bit easier - you can develop roles for use with Vlad that don't necessarily need to be part of Vlad (that's not to say that it won't) - this allows for more sandboxed development which in turn better supports experimentation and niche use cases (I'm not saying what you propose is experimental or niche, I'm just trying to encourage this workflow for _all_ new features that may warrant an entire new role or more). Once a role is fully fleshed out it's then just a case of either adding it to Vlad's requirements.yml or someone using it as part of their custom play.

**Comment by wizonesolutions** [comment]
Hrm. Seems like I can structure a custom play like a role. But it's not exactly like a role, and that's kind of what gets me...I'll have to refactor to make it a real role. I'm probably better off just developing like we said before...work on a role in the `ext_roles` directory and then make it its own Git repo when I'm satisfied. Something like that?

I'm still open to doing a custom play if it won't be extra work, though. I was looking  at https://github.com/danbohea/vlad_custom to get an idea of the structure.

**Comment by dixhuit** [comment]
> Hrm. Seems like I can structure a custom play like a role. But it's not exactly like a role, and that's kind of what gets me...I'll have to refactor to make it a real role.

Or create a really minimal custom play that _uses_ your role (that would be a handy custom play to have to hand generally) and then you can develop your role as a proper role. I CAN'T STOP SAYING ROLE.

> I'm probably better off just developing like we said before...work on a role in the ext_roles directory and then make it its own Git repo when I'm satisfied. Something like that?

Sure - that can work too if you'd prefer.

> I'm still open to doing a custom play if it won't be extra work, though. I was looking at https://github.com/danbohea/vlad_custom to get an idea of the structure.

That repo has got thinner and thinner as custom roles became custom plays and as more of my custom stuff got refactored into less opinionated stuff in Vlad itself (in fact - it's probably time to remove the hosting tools stuff now that it's in(ish) Vlad dev - thanks for reminding me).

**Comment by wizonesolutions** [comment]
Was implemented in main branch.
