### ISSUE TITLE
Update README, meta to match other changes.

### ISSUE THREAD

**Issue by benjifisher** [hashbangcode/ansible-role-pantheon-cli#3]
While browsing your code, I noticed a few small problems:
1. The main README mentions the "current default" of `pantheon_cli_version` that is not up to date with `defaults/main.yml`.
2. A recent commit switched from `sudo` to `become`, which requires Ansible 1.9+, but `meta/main.yml` lists `min_ansible_version: 1.4`.

**Comment by dixhuit** [comment]
Thanks for the heads up. Just fixed.
